# Generated by Django 5.1.4 on 2025-04-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
