# Generated by Django 5.1.4 on 2025-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
