# Generated by Django 5.1.4 on 2025-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('ticket', 'phone_number')},
        ),
    ]
