# Generated by Django 5.1.4 on 2025-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_eventsignup_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='finish_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='road_profile_tag',
        ),
        migrations.RemoveField(
            model_name='event',
            name='road_surface',
        ),
        migrations.RemoveField(
            model_name='event',
            name='seconde_picture',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='relativ_phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
