# Generated by Django 5.1.4 on 2025-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event_location_eventsignup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
