# Generated by Django 5.1.4 on 2025-01-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_event_location_alter_eventsignup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.event'),
        ),
    ]
