# Generated by Django 5.1.4 on 2025-01-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pages.ticket'),
            preserve_default=False,
        ),
    ]
