# Generated by Django 5.1.4 on 2025-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_event_category_remove_event_finish_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title_picture',
            new_name='banner_image',
        ),
        migrations.AddField(
            model_name='event',
            name='route_image',
            field=models.ImageField(default=1, upload_to='event'),
            preserve_default=False,
        ),
    ]
