# Generated by Django 5.1.4 on 2025-01-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_eventsignup_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='event',
        ),
    ]
