# Generated by Django 5.1.4 on 2025-02-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_title_picture_event_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='pages.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='finish_address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('all', 'all genders')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='other_tags',
            field=models.ManyToManyField(related_name='event', to='pages.tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='road_profile_tag',
            field=models.ManyToManyField(related_name='road', to='pages.tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='road_surface',
            field=models.ManyToManyField(related_name='surface', to='pages.tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('up_comming_competition', 'up_comming_competition'), ('in_progress_competition', 'in_progress_competition'), ('closed_competition', 'closed_competition')], default='up_comming_competition', max_length=25),
        ),
    ]
