# Generated by Django 5.1.4 on 2025-01-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_eventsignup_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
