# Generated by Django 5.1.4 on 2025-01-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_eventsignup_first_name_eventsignup_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='user',
        ),
    ]
