# Generated by Django 5.1.4 on 2025-02-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_event_team_member_fullname_event_team_member_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_member_fullname',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_member_pic',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_member_position',
        ),
    ]
