# Generated by Django 5.1.4 on 2025-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_event_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateField(),
        ),
    ]
