# Generated by Django 5.1.4 on 2025-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_teammember_event_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_member',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
