# Generated by Django 5.1.4 on 2025-01-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('up_comming_competition', 'up_comming_competition'), ('in_progress_competition', 'in_progress_competition'), ('closed_competition', 'closed_competition')], max_length=25),
        ),
    ]
