# Generated by Django 5.1.4 on 2025-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_eventsignup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='relativ_last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='relativ_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='relativ_phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
