# Generated by Django 5.1.4 on 2025-02-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_event_team_member_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='team_member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='pages.teammember'),
            preserve_default=False,
        ),
    ]
