# Generated by Django 5.1.4 on 2025-01-18 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_eventsignup_relativ_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='singup_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
