# Generated by Django 5.1.4 on 2025-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_teammember_event_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
