# Generated by Django 5.1.4 on 2025-01-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_eventsignup_singup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='evtry_price',
        ),
    ]
