# Generated by Django 5.1.4 on 2025-02-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_eventsignup_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_runner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
