# Generated by Django 5.1.4 on 2025-02-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_event_max_runner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_member',
        ),
        migrations.AddField(
            model_name='teammember',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
            preserve_default=False,
        ),
    ]
