# Generated by Django 5.1.4 on 2025-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_tags_remove_event_road_profile_event_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='other_tags',
        ),
        migrations.AddField(
            model_name='event',
            name='road_profile_tag',
            field=models.ManyToManyField(related_name='road', to='pages.tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='road_surface',
            field=models.ManyToManyField(related_name='surface', to='pages.tags'),
        ),
    ]
