# Generated by Django 5.1.4 on 2025-03-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_tags_event_other_tags_event_road_profile_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='seconde_picture',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_picture',
            new_name='route_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_data',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_runner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='event', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='relativ_phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_ticket', to='pages.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('ticket', 'phone_number')},
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.URLField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=600)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsers', to='pages.event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='team_member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='pages.event')),
            ],
        ),
    ]
