# Generated by Django 5.1.4 on 2025-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='phone_number',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
