# Generated by Django 5.1.4 on 2025-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_seconde_picture_event_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='T_Shirt_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X Large'), ('2xl', '2X Large')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
