# Generated by Django 5.1.4 on 2025-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_eventsignup_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
