# Generated by Django 5.1.4 on 2025-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_id_pic_eventsignup_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='id_number',
            field=models.CharField(max_length=12),
        ),
    ]
