# Generated by Django 5.1.4 on 2025-02-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_eventsignup_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_ticket', to='pages.ticket'),
        ),
    ]
