# Generated by Django 5.1.4 on 2025-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_eventsignup_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_to_social_media',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
