# Generated by Django 5.1.4 on 2025-04-08 12:43

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_event_link_to_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[pages.models.validate_iran_phone_number]),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='relativ_phone_number',
            field=models.CharField(max_length=11, validators=[pages.models.validate_iran_phone_number]),
        ),
    ]
