# Generated by Django 5.1.4 on 2025-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_event_start_time_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
