# Generated by Django 5.1.4 on 2025-04-10 07:42

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distanc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.TimeField(default="00:00:00"),
        ),
    ]
