# Generated by Django 5.1.4 on 2025-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_ticket_distanc_ticket_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
