# Generated by Django 5.1.4 on 2025-04-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_ticket_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='distanc',
        ),
    ]
