# Generated by Django 5.1.4 on 2025-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_ticket_distanc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distanc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
