# Generated by Django 5.1.4 on 2025-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_ticket_distanc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='distanc',
            field=models.IntegerField(),
        ),
    ]
