# Generated by Django 5.1.4 on 2025-01-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('UP', 'UnApproved')], max_length=2, null=True),
        ),
    ]
